name: line_dot_dot
description: A command line interaction toolkit.
version: 0.0.2
repository: https://github.com/louiskhchan/line_dot_dot

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
